language: python
python: 
  - "2.7"
install: pip install -r requirements.txt
script: python test.py
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 5b7d3c76542fdde41835cf28453af9d838003962 #${GITHUB_TOKEN} #5b7d3c76542fdde41835cf28453af9d838003962
  keep_history: true
  on:
    branch: master

